version: '3'
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar-db-data:

services:
  eureka-server:
    image: registry-service-tnb
    pull_policy: never
    ports:
      - "8761:8761"

  tax-calculation-service:
    image: tax-calculation-service
    pull_policy: never
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  tax-rate-service:
    image: tax-rate-service
    pull_policy: never
    ports:
      - "8091:8091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server 
      - tax-rate-db

  tax-rate-db:
    image: mysql:latest
    pull_policy: never
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tax-rate-database
      MYSQL_PASSWORD: root

  terrain-service:
    image: terrain-service-tnb
    pull_policy: never
    ports:
      - "8092:8092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - terrain-db

  terrain-db:
    image: mysql:latest
    pull_policy: never
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terrain-database
      MYSQL_PASSWORD: root

  gateway-service:
    image: gateway-service-tnb
    pull_policy: never
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
  
  