spring:
  cloud:
    gateway:
      routes:
        - id: terrain-service
          uri: lb://terrain-service
          predicates:
            - Path=/terrain-service/**
          filters:
            - RewritePath=/terrain-service/(?<segment>.*), /$\{segment}

        - id: tax-rate-service
          uri: lb://tax-rate-service
          predicates:
            - Path=/tax-rate-service/**
          filters:
            - RewritePath=/tax-rate-service/(?<segment>.*), /$\{segment}

        - id: tax-calculation-service
          uri: lb://tax-calculation-service
          predicates:
            - Path=/tax-calculation-service/**
          filters:
            - RewritePath=/tax-calculation-service/(?<segment>.*), /$\{segment}

  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8099


